baseurl = "https://www.baidu.com/"
languageCode = "zh-CN"
title = "我的第一个博客"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about/"
    Weight = 2
  [[Menu.Main]]
    Name = "技术文章"
    URL = "/categories/技术文章/"
    Weight = 3